[project]
name = "manim_speech"
version = "0.3.0-dev"
description = "Manim plugin for adding speech to videos."
authors = [{ name = "Celeste Ma", email = "mtcelestema@proton.me" }]
requires-python = ">=3.12"
readme = "README.md"
license = "MIT"
keywords = [
    "manim",
    "speech",
    "voiceover",
    "tts",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Multimedia :: Sound/Audio :: Speech",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "manim>=0.20.1,<0.21",
    "pydantic>=2.8.0,<3",
    "mutagen>=1.47.0,<2",
    "polib>=1.2.0,<2",
    "python-slugify>=8.0.4,<9",
]

[project.optional-dependencies]
openai = ["openai>=2.49.0,<3"]
elevenlabs = ["elevenlabs>=2.59.0,<3"]
whisper = ["openai-whisper"]
assemblyai = ["assemblyai>=0.64.0,<0.65"]
deepl = ["deepl>=1.30.0,<2"]
chinese = ["langconv>=0.3.0,<0.4"]

[project.urls]
Homepage = "https://github.com/MtCelesteMa/manim-speech"
Repository = "https://github.com/MtCelesteMa/manim-speech"
"Bug Tracker" = "https://github.com/MtCelesteMa/manim-speech/issues"

[dependency-groups]
dev = [
    "ruff>=0.16.0",
    "ty>=0.0.64",
]

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]
